import type { Metadata } from 'next'

import LeftPage from '../components/organisms/left/page'
import ViewPage from '../components/organisms/View/page'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#171717]">
        <div className="mx-auto max-w-[78rem]">
          <div className="flex flex-col gap-4 md:mt-5 md:flex-row">
            <LeftPage />
            {children}
            <ViewPage />
          </div>
        </div>
      </body>
    </html>
  )
}
